spring:
  datasource:
    url: jdbc:mysql:///ly_admin
    username: root
    password: 123456
  mvc:
    format:
      date-time: yyyy-MM-dd HH:mm:ss
      date: yyyy-MM-dd
      time: HH:mm:ss

server:
  # 如果配置了反向代理, 需要使用此项(or framework)来处理 server url, 反向代理需要配置x-forwarded-header
  forward-headers-strategy: native
# Sa-Token配置
sa-token:
  token-name: token
  is-share: false
  token-style: uuid
app:
  file:
    upload-path: E:/xyf/tmp

logging:
  file:
    name: ./logs/ly-admin.log
  logback:
    rollingpolicy:
      max-history: 30
      max-file-size: 10MB
  pattern:
    console: "%clr(%d{${LOG_DATEFORMAT_PATTERN:HH:mm:ss.SSS}}){faint} \
              %clr(${LOG_LEVEL_PATTERN:%5p}) \
              %clr(%X{userId}){red} \
              %clr(%logger{39}){cyan}\
              %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"

#mybatis plus 设置
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleted
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl