spring:
  datasource:
    druid:
      url: jdbc:mysql:///ly_admin
      username: root
      password: 123456
server:
  # 如果配置了反向代理, 需要使用此项(or framework)来处理 server url, 反向代理需要配置x-forwarded-header
  forward-headers-strategy: native
# Sa-Token配置
sa-token:
  token-name: token
  is-share: false
  token-style: uuid
app:
  file:
    upload-path: E:/xyf/tmp

# spring doc
springdoc:
  api-docs:
    path: /doc
logging:
  # IDEA某版本会提示过期, 原因是替换为logging.file.name.忽略即可
  file:
    name: ./logs/ly-admin.log
  pattern:
    console: '%d{HH:mm:ss.SSS} [%thread] %X{userId} %highlight(%-5level) %cyan(%logger{20}:%L) - %msg%n'
    file: '%d{HH:mm:ss.SSS} [%thread] %X{userId} %-5level %cyan(%logger{20}:%L) - %msg%n'
  logback:
    rollingpolicy:
      max-history: 30
      max-file-size: 100MB
#mybatis plus 设置
mybatis-plus:
  global-config:
    db-config:
      id-type: ASSIGN_ID
      # 默认数据库表下划线命名
      table-underline: true
      logic-delete-field: deleted
  configuration:
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
