spring:
  datasource:
    url: jdbc:mysql:///ly_admin
    username: root
    password: 123456
server:
  # 如果配置了反向代理, 需要使用此项(or framework)来处理 server url, 反向代理需要配置x-forwarded-header
  forward-headers-strategy: native
# Sa-Token配置
sa-token:
  token-name: token
  is-share: false
  token-style: uuid
app:
  file:
    upload-path: E:/xyf/tmp
# spring doc
springdoc:
  api-docs:
    path: /doc
logging:
  file:
    name: ./logs/ly-admin.log
  # todo: 注入用户id
  logback:
    rollingpolicy:
      max-history: 30
      max-file-size: 10MB
  pattern:
    console: >-
      %clr(%d{${LOG_DATEFORMAT_PATTERN:HH:mm:ss.SSS}}){faint}
      %clr(${LOG_LEVEL_PATTERN:%5p})
      %clr(${PID:- }){magenta}
      %clr(---){faint}
      %clr(%X{userId}){red}
      %clr([%15.15t]){faint}
      %clr(%-40.40logger{39}){cyan}
      %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}

#mybatis plus 设置
mybatis-plus:
  global-config:
    db-config:
      id-type: ASSIGN_ID
      # 默认数据库表下划线命名
      table-underline: true
      logic-delete-field: deleted
  configuration:
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl